[tool.poetry]
name = "alfalfa-client"
version = "0.1.0-dev5"
description = "A standalone client for the NREL Alfalfa application"
authors = [
    'Kyle Benne <kyle.benne@nrel.gov>',
    'Brian Ball <brian.ball@nrel.gov>',
    'Cory Mosiman <cory.mosiman@nrel.gov>',
    'Nicholas Long <nicholas.long@nrel.gov>',
    'Willy Bernal <willy.bernalheredia@nrel.gov>',
    'Yanfei Li <yanfei.li@nrel.gov>'
]
readme = 'README.md'
license = 'LICENSE.txt'

[tool.poetry.dependencies]
python = "^3.6"
pandas = "0.24.2"
requests-toolbelt = "0.9.1"
importlib-metadata = {version = "^1.0", python = "<3.8"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
tox = "^3.20.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
